language: node_js
node_js:
  - "stable"
cache: npm
install:
  - npm install
script:
  - npm run build
  - npm run dev
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build
 on:
   branch: master