language: node_js
node_js:
  - 17
cache: npm
install:
  - npm install
script:
  - npm run build
  - npm run preview
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 keep_history: true
 on:
   branch: master